---
abstract: 'Create Blowfish-specific object methods for Rose::DB::Object-derived objects.'
author:
  - 'Holger Rupprecht <holger.rupprecht@gmx.de>'
build_requires:
  Rose::DBx::TestDB: '0.05'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rose-DBx-Object-MakeMethods-EKSBlowfish
provides:
  Rose::DBx::Object::MakeMethods::EKSBlowfish:
    file: lib/Rose/DBx/Object/MakeMethods/EKSBlowfish.pm
    version: '0.07'
  Rose::DBx::Object::Metadata::Column::EKSBlowfish:
    file: lib/Rose/DBx/Object/Metadata/Column/EKSBlowfish.pm
    version: '0.07'
requires:
  Crypt::Eksblowfish::Bcrypt: '0.009'
  Rose::DB: '0.77'
  Rose::DB::Object: '0.804'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.07'
